stages:
  - build
  - deploy

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cache/.cargo
  CARGO_TARGET_DIR: $CI_PROJECT_DIR/.cache/.cargo-target

cache:
  key: "$CI_COMMIT_REF_SLUG-$CI_JOB_NAME"
  paths:
    - .cache

before_script:
  - mkdir -p .cache
  - mkdir -p .artifacts

build-web:
  stage: build
  image: registry.gitlab.com/kuviman/dock.rs/web
  script:
    - cargo web deploy --release
    - mv $CARGO_TARGET_DIR/deploy .artifacts/web
  artifacts:
    paths:
      - .artifacts

pages:
  stage: deploy
  dependencies:
    - build-web
  image: alpine
  script:
    - mv .artifacts/web public
  artifacts:
    paths:
      - public
